-- Supabase / PostgreSQL Schema untuk LBQueen POS

-- Tabel Kategori (Skincare, Obat Minum, Tindakan, dll)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- Tabel Produk (Barang & Obat & Treatment & Aset)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('Treatment Care & Beauty', 'Product Care & Beauty', 'Treatment', 'Retail Produk', 'Barang Kantor', 'Aset Karyawan')),
    purchase_price DECIMAL(10,2) NOT NULL,
    selling_price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0,
    unit VARCHAR(50), -- e.g., Pcs, Botol, Sesi
    image_url TEXT NULL, -- Link ke foto produk/treatment
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Customers (Dengan fitur Membership)
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(50) NULL,
    is_member BOOLEAN DEFAULT FALSE,
    join_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Kolom login portal pelanggan
    username VARCHAR(100) UNIQUE NULL,      -- e.g., "sriwahyuni" (dari nama, lowercase, no spasi)
    password_hash TEXT NULL,               -- bcrypt/base64 hash dari password plain
    password_plain VARCHAR(100) NULL       -- untuk tampil di admin: "SW-M-5" format
);

-- ALTER jika tabel sudah ada (jalankan ini di Supabase SQL Editor):
-- ALTER TABLE customers ADD COLUMN IF NOT EXISTS username VARCHAR(100) UNIQUE;
-- ALTER TABLE customers ADD COLUMN IF NOT EXISTS password_hash TEXT;
-- ALTER TABLE customers ADD COLUMN IF NOT EXISTS password_plain VARCHAR(100);

-- Tabel Customer Orders (Log pemesanan via WhatsApp)
CREATE TABLE customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    customer_name VARCHAR(150) NOT NULL,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    ordered_at TIMESTAMPTZ DEFAULT NOW(),
    status VARCHAR(50) DEFAULT 'pending'  -- pending | confirmed | cancelled
);

-- ALTER jika tabel sudah ada:
-- CREATE TABLE IF NOT EXISTS customer_orders (
--   id BIGSERIAL PRIMARY KEY,
--   customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
--   customer_name VARCHAR(150) NOT NULL,
--   product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
--   product_name TEXT NOT NULL,
--   ordered_at TIMESTAMPTZ DEFAULT NOW(),
--   status VARCHAR(50) DEFAULT 'pending'
-- );

-- Tabel Vouchers Khusus Membership
CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    discount_amount DECIMAL(15,2) NOT NULL, -- Potongan Rupiah langsung (Fleksibel)
    min_purchase DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Transaksi Kasir (Header) - Di-update dengan dukungan voucher & member
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    user_id BIGINT, -- Kasir
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    voucher_id BIGINT REFERENCES vouchers(id) ON DELETE SET NULL,
    subtotal DECIMAL(15,2) NOT NULL,
    discount_applied DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) NOT NULL,
    payment DECIMAL(15,2) NOT NULL,
    change_amount DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Detail Transaksi (Item yang dibeli)
CREATE TABLE transaction_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL
);

-- Tabel Users (Dengan tambahan role jika perlu)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('admin', 'kasir', 'owner', 'digital_ops')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data awal Users
INSERT INTO users (username, password, name, role) 
VALUES 
('admin', 'adminlbqueen', 'Super Admin', 'admin'),
('adel', 'adel123lbq', 'Adel', 'kasir'),
('owner', 'ownerlbq', 'Owner', 'owner'),
('ops', 'opslbqueen', 'Tim Digital Ops', 'digital_ops');

-- Update 1.6: Voucher per produk & Produk Set
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_set BOOLEAN DEFAULT FALSE;
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES products(id) ON DELETE SET NULL;

-- Update 1.7: New Categories for Treatment Care & Beauty
INSERT INTO categories (name) VALUES 
('Beauty facial & body'),
('Eyelash'),
('Nail art'),
('Eyebrow')
ON CONFLICT DO NOTHING;

