-- ============================================================
-- LBQueen POS — Database Migration v2 (Fixed)
-- Fitur: Varian Produk + Retail Sub-Kategori Baru
--
-- Cara pakai:
--   1. Buka Supabase → SQL Editor
--   2. Copy seluruh isi file ini
--   3. Klik RUN (atau tekan Ctrl+Enter)
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- STEP 1: Drop constraint lama (tanpa tambah yang baru dulu)
-- ────────────────────────────────────────────────────────────
DO $$
DECLARE
  cname TEXT;
BEGIN
  SELECT conname INTO cname
  FROM pg_constraint
  WHERE conrelid = 'products'::regclass
    AND contype = 'c'
    AND conname LIKE '%type%';

  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE products DROP CONSTRAINT %I', cname);
    RAISE NOTICE 'Dropped: %', cname;
  ELSE
    RAISE NOTICE 'No type constraint found.';
  END IF;
END $$;


-- ────────────────────────────────────────────────────────────
-- STEP 2: Update data lama DULU sebelum pasang constraint baru
-- ────────────────────────────────────────────────────────────
UPDATE products
SET type = 'Retail Beauty'
WHERE type = 'Retail Produk';


-- ────────────────────────────────────────────────────────────
-- STEP 3: Pasang constraint baru (data sudah aman)
-- ────────────────────────────────────────────────────────────
ALTER TABLE products
  ADD CONSTRAINT products_type_check
  CHECK (type IN (
    'Treatment',
    'Treatment Care & Beauty',
    'Product Care & Beauty',
    'Retail Nail',
    'Retail Eyelash',
    'Retail Beauty',
    'Barang Kantor',
    'Aset Karyawan'
  ));


-- ────────────────────────────────────────────────────────────
-- STEP 4: Buat tabel product_variants
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product_variants (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  variant_name VARCHAR(150) NOT NULL,
  price        DECIMAL(10, 2) NOT NULL,
  stock        INT DEFAULT 0,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id
  ON product_variants(product_id);


-- ────────────────────────────────────────────────────────────
-- STEP 5: Tambah kolom varian di transaction_details
-- ────────────────────────────────────────────────────────────
ALTER TABLE transaction_details
  ADD COLUMN IF NOT EXISTS variant_id   BIGINT
    REFERENCES product_variants(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS variant_name TEXT NULL;


-- ────────────────────────────────────────────────────────────
-- STEP 6: RLS untuk tabel product_variants
-- ────────────────────────────────────────────────────────────
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'product_variants'
      AND policyname = 'Allow all on product_variants'
  ) THEN
    EXECUTE $p$
      CREATE POLICY "Allow all on product_variants"
        ON product_variants FOR ALL
        USING (true) WITH CHECK (true)
    $p$;
    RAISE NOTICE 'Policy created.';
  ELSE
    RAISE NOTICE 'Policy already exists.';
  END IF;
END $$;


-- ────────────────────────────────────────────────────────────
-- STEP 7: Verifikasi hasil
-- ────────────────────────────────────────────────────────────

-- Jumlah produk per tipe setelah migrasi
SELECT type, COUNT(*) AS jumlah
FROM products
GROUP BY type
ORDER BY type;

-- Struktur tabel product_variants
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'product_variants'
ORDER BY ordinal_position;

-- Kolom baru di transaction_details
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'transaction_details'
  AND column_name IN ('variant_id', 'variant_name');
